version: 2
jobs:
  build:
    working_directory: ~/mern-starter
    docker:
      - image: circleci/node:10.15.0
  steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm'
      - run:
          name: node-version
          command: 'sudo npm install -g npm'   
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
